language: elm

env:
  global:
    - PUBLIC_URL="https://arkham.github.io/elm-nokia-composer"

install:
  - npm install -g elm@0.19.1-3
  - npm install -g elm-test@0.19.1

script:
  - npm install -g parcel-bundler
  - npm run build

deploy:
  github-token: $GITHUB_TOKEN
  local-dir: dist
  provider: pages
  skip-cleanup: true
  on:
    branch: master
